aws:
  access-key: AKIAWD3DXWDNWHDXXGXO
  region: US_EAST_2

roles:
  discord:
    dm:
      defaultRole: NORMAL
      mappings:
        - userId: 248612704019808258
          role: ADMIN
    guild:
    - guildId: 423976318082744321
      defaultRole: BLOCKED
      mappings:
        - roleId: 423978119980908545
          role: ADMIN
        - roleId: 83105436806418432
          role: MODERATOR
        - roleId: 448504831469027359
          role: NORMAL