package com.github.milomarten.fracktail.core.birthday.v3;

import java.time.LocalDate;
import java.time.MonthDay;
import java.time.Year;
import java.util.*;

public class ScrollingCalendar<T> {
    private Map<Year, CalendarForYear<T>> pages;
    private List<EventGenerator<T>> eventGenerators;

    public ScrollingCalendar() {
        this.pages = new HashMap<>();
        this.eventGenerators = new ArrayList<>();
    }

    private CalendarForYear<T> getOrCreate(Year year) {
        if (pages.containsKey(year)) {
            return pages.get(year);
        } else {
            var calendar = pages.computeIfAbsent(year, CalendarForYear::new);

            eventGenerators.stream()
                    .map(eg -> eg.createForYear(year))
                    .filter(Objects::nonNull)
                    .forEach(eaw -> calendar.addEvent(MonthDay.from(eaw.when()), eaw.event()));

            return calendar;
        }
    }

    private void updateCalendarWhenEventAdded(EventGenerator<T> eventGenerator) {
        for (var year : pages.keySet()) {
            var event = eventGenerator.createForYear(year);
            if (event != null) {
                pages.get(year).addEvent(MonthDay.from(event.when()), event.event());
            }
        }
    }

    private void updateCalendarWhenEventRemoved(EventGenerator<T> eventGenerator) {
        for (var year : pages.keySet()) {
            var event = eventGenerator.createForYear(year);
            if (event != null) {
                pages.get(year).removeEvent(MonthDay.from(event.when()), event.event());
            }
        }
    }

    /**
     * Add a recurring event to the calendar.
     * @param eventGenerator The function which generates an event
     */
    public void addRecurringEvent(EventGenerator<T> eventGenerator) {
        this.eventGenerators.add(eventGenerator);
        updateCalendarWhenEventAdded(eventGenerator);
    }

    /**
     * Remove a recurring event from the calendar.
     * There are certain expected prerequisites here:
     * 1. The input eventGenerator equals() one already present in this calendar. If it does not, nothing happens.
     * 2. The event generated by the eventGenerator for a given year must equals() the event it generated previously for
     * that same year. If it does not, that year's event is not cleaned, although regenerating will properly remove it.
     * @param eventGenerator The function which generates an event
     */
    public void removeRecurringEvent(EventGenerator<T> eventGenerator) {
        if(this.eventGenerators.remove(eventGenerator)) {
            updateCalendarWhenEventRemoved(eventGenerator);
        }
    }

    /**
     * Get the events immediately after some origin time
     * For efficiency, the calendar will only check up until the last day of the calendar year after the provided
     * start time. For my purposes, this is enough.
     * @param start The time to begin searching
     * @param exclusive If true, start is ignored
     * @return The events that are occurring after the start time
     */
    public EventAndWhen<List<T>> getNextEvents(LocalDate start, boolean exclusive) {
        var year = Year.from(start);
        var md = MonthDay.from(start);
        var events = getOrCreate(year).getNextEvents(md, exclusive);
        if (events == null) {
            events = getOrCreate(year.plusYears(1)).getFirstEvents();
        }
        return events;
    }

    /**
     * Get the events immediately before some origin time
     * For efficiency, the calendar will only check up until the first day of the calendar year before
     * the provided start time. For my purposes, this is enough.
     * @param start The time to begin searching
     * @param exclusive If true, start is ignored
     * @return The events that are occurring before the start time
     */
    public EventAndWhen<List<T>> getPreviousEvents(LocalDate start, boolean exclusive) {
        var year = Year.from(start);
        var md = MonthDay.from(start);
        var events = getOrCreate(year).getPreviousEvents(md, exclusive);
        if (events == null) {
            events = getOrCreate(year.minusYears(1)).getLastEvents();
        }
        return events;
    }

    /**
     * A function which generates events.
     * Given the provided year, generate zero or one events that occur on that year.
     * @param <T> The event type
     */
    public interface EventGenerator<T> {
        /**
         * Create an event for a given year
         * @param year The year to create for
         * @return The event and its time, or null if not applicable for this year.
         */
        EventAndWhen<T> createForYear(Year year);
    }
}
