name: Docker Image CI

on:
  push:
    tags: 'v*'
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3.13.0
      with:
        java-version: 17
        
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.8.0
      
    # - name: Build and Push to Docker
    #   run: |
    #     docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
    #     docker image build . --file --tag fracktail4:latest --tag fracktail4:${{ github.ref_name }}
    #     docker image push --all-tags fracktail4
